=== osrg/namazu/doc/schema/event.json
{
    "id": "http://github.com/osrg/namazu/schema/event.json#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "schema for an event",
    "additionalProperties": true,
    "required": [
	"uuid",
	"entity",
	"type",
	"class",
	"deferred"
    ],
    "type": "object",
    "properties": {
	"uuid": {
	    "type": "string"
	},
	"entity": {
	    "type": "string"
	},
	"type": {
	    "type": "string"
	},
	"class": {
	    "type": "string"
	},
	"deferred": {
	    "type": "boolean"
	},
	"option": {
	    "type": "object"
	}
    }
}

=== osrg/namazu/schema/example/event/PacketEvent.json
{
    "type": "event",
    "class": "PacketEvent",
    "entity": "_earthquake_ether_inspector",
    "uuid": "1f13eaa6-4b92-45f0-a4de-1236081dc649",
    "deferred": true,
    "option": {
        "src_process": "zksrv1",
        "dst_process": "zksrv3",
	"message": {
            "ZkQuorumPacket": {
		"AckQP": {
                    "zxid_low": 0,
                    "zxid_high": 1
		}
	    }
        }
    }
}
